function downloadtec(year, tec_dir, overwrite)
% Download a whole year of TEC data from Madrigal Database 
% (http://cedar.openmadrigal.org)using their APIs provided at 
% http://cedar.openmadrigal.org/madrigalDownload
% 
% year (string) - year of the TEC data to download
% tec_dir (string) - target directory to save the downloaded data
% overwrite (bool) - when false, no data will be downloaded if the subfolder 
%                    tec_dir/year already exists.
% 
% Note: please make sure the function "globalDownload" is available in 
% MATLAB's search path and wget is installed in your machine.
    
    % add wget to MATLAB environmental variable PATH
    setenv('PATH', [getenv('PATH') ':/usr/local/bin:/opt/local/bin']);
    
    % create a subfolder in tec_dir to save the current year's data
    folder = [tec_dir '/' year];
    folder_no_esc = strrep(folder,'\',''); % in case the given tec_dir has escape characters
    if ~exist(folder_no_esc,'dir')
        mkdir(folder_no_esc);
    elseif ~overwrite
        warning(['target directory already exists, no data has been downloaded, '...
            'set overwrite to true to download the data to this directory: ' ...
            folder_no_esc])
        return
    end
    
    % call Madrigal API to download data
    globalDownload('http://cedar.openmadrigal.org', ...
        folder, ...
        'Jiaen+Ren', ...
        'jiaenren@umich.edu', ...
        'University+of+Michigan%E2%80%93Ann+Arbor', ...
        'hdf5', ...
        datenum(['01-Jan-' year ' 00:00:00']), ...
        datenum(['31-Dec-' year ' 23:59:59']), ...
        8000, ...
        [3500], ...
        '', ...
        '');
end